### ISSUE TITLE
Catalogar quais políticos votaram a favor ou contra determinada proposta do site

### ISSUE THREAD

**Issue by vmourac** [ourcities/panela-de-pressao#44]
Atualmente cada proposta no site inclui uma lista de e-mails de políticos que serão "pressionados" a aprovar determinada proposta.

Uma sugestão de feature pro site seria catalogar quais políticos votaram a favor ou contra propostas que determinado usuário "botou pressão".

Ao final de uma determinada campanha ("Vitória!" ou "Não deu"), pode-se obter as informações de voto (contra ou a favor) de cada político envolvido na proposta e correlacionar com os politicos que foram "pressionados".

Dessa maneira o site poderá informar para seus usuários quais políticos são mais alinhados com seus respectivos eleitores (quais políticos apoiaram ou não as propostas que seus usuários "botaram pressão").
Em época de eleição, essa ferramenta seria de extrema valia, já que um usuário terá "de graça" sugestões de quais políticos votar (os políticos que efetivamente apoiaram as ideias que o usuário se identifica)

**Comment by lpirola** [comment]
Obrigado pelo feedback @vmourac!

Estamos centralizando em uma única ferramenta o gerenciamento de novas funcionalidades.

Você pode visitar [nosso backlog clicando aqui](https://www.pivotaltracker.com/n/projects/1063622/search?q=label%3A%22paneladepressao%22). O seu comentário foi [criado e você pode acessar aqui](https://www.pivotaltracker.com/story/show/120292719).

Caso tenha mais ideias, pode clicando no ícone "+" no nosso [novo gerenciador](https://www.pivotaltracker.com/n/projects/1063622).
